# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.10-slim

WORKDIR /app

# copy source code
COPY . /app

# install dependencies
RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "server.py"]
